# Generated by Django 5.2.7 on 2025-10-31 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True, max_length=500)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('topics', models.CharField(blank=True, help_text='Comma-separated topics', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=100)),
                ('recipe_revision', models.CharField(blank=True, help_text='Git/hash of recipe', max_length=64)),
                ('recipe_file', models.FileField(blank=True, null=True, upload_to='recipes/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.package')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('package', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BinaryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, help_text="Conan's unique package ID for this binary", max_length=64, unique=True)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('arch', models.CharField(blank=True, max_length=50)),
                ('compiler', models.CharField(blank=True, max_length=50)),
                ('compiler_version', models.CharField(blank=True, max_length=50)),
                ('build_type', models.CharField(blank=True, max_length=50)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('binary_file', models.FileField(blank=True, null=True, upload_to='binaries/')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binaries', to='packages.packageversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('packages', models.ManyToManyField(blank=True, related_name='topic_tags', to='packages.package')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_requirement', models.CharField(help_text="e.g., '>=1.0.0', '[1.0.0-2.0.0]'", max_length=100)),
                ('dependency_type', models.CharField(choices=[('requires', 'Requires'), ('build_requires', 'Build Requires'), ('test_requires', 'Test Requires')], default='requires', max_length=20)),
                ('requires_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='packages.package')),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='packages.packageversion')),
            ],
            options={
                'verbose_name_plural': 'Dependencies',
                'unique_together': {('package_version', 'requires_package', 'dependency_type')},
            },
        ),
    ]
