# Generated by Django 5.2.7 on 2025-11-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='recipe_content',
            field=models.TextField(blank=True, help_text='Content of conanfile.py'),
        ),
    ]
