# Generated by Django 5.2.7 on 2025-11-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packageversion_recipe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarypackage',
            name='dependency_graph',
            field=models.JSONField(blank=True, default=dict, help_text='Full Conan dependency graph with resolved package_ids'),
        ),
    ]
