# Generated by Django 5.2.7 on 2025-11-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_add_dependency_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='conan_version',
            field=models.CharField(blank=True, help_text='Version of Conan used to create this package', max_length=50),
        ),
    ]
