# Generated by Django 5.2.7 on 2025-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packageversion_conan_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarypackage',
            name='rust_crate_file',
            field=models.FileField(blank=True, help_text='Generated Rust -sys crate archive', null=True, upload_to='rust_crates/'),
        ),
    ]
